### ISSUE TITLE
Update the theme section of landing page

### ISSUE THREAD

**Issue by achan** [openmcac/landing#1]
MCAC's new theme for 2015 is "Heaven Bound."

We need to find/create a new graphic for this theme.
- keep the image at 1920px wide
- we want to keep this landing page responsive, so please use [Google web fonts](https://www.google.com/fonts) in your design. This allows us to adapt to mobile/tablet/desktop views.
- see creationswap.com for sample images we can use

**Comment by achan** [comment]
If you've got any questions or ideas you can post them here! @atsiang

**Comment by chohinlo** [comment]
Is there a bible verse for this year's church theme?

**Comment by achan** [comment]
I'll have to get that information this Sunday...

**Comment by ghost** [comment]
![heavenbound](https://cloud.githubusercontent.com/assets/10411213/5810886/81c50d96-a01b-11e4-83e9-5e2a9e4ea5e3.jpg)

**Comment by achan** [comment]
Really good job @atsiang! Now what need need is a copy of the background only and the name of the Google Web Font that you used.

Can you give us a Dropbox link of the background at full resolution?

**Comment by ghost** [comment]
https://www.dropbox.com/s/kb5027lmex98o3f/heavenbound.jpg?dl=0

**Comment by ghost** [comment]
Oh and the font was Pacifico

**Comment by achan** [comment]
Hey @atsiang, do you still have the image? The link no longer works...

**Comment by ghost** [comment]
yeah sorry I accidentally moved it, but I updated the link like yesterday so it should work now
